inherit_from: configs/ScanNet/scannet.yaml
mode: rgbd
mapping:
  device: "cuda:0"
  bound: [[-5.0, 14.0],[-4.0,5.0],[-6.0, 4.0]]
meshing:
  gt_mesh_path: '/home/yongqich/research/data/ScanNet/scans/scene0181_00/scene0181_00_vh_clean.ply'
data:
  input_folder: /home/yongqich/research/data/ScanNet/scans/scene0181_00
  output: /home/yongqich/research/GO-SLAM/output/scannet/0181/rgbd
