inherit_from: ./configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-5, 4], [-5, 6], [-6, 4]]

meshing:
  gt_mesh_path: '/home/yongqich/research/data/ScanNet/scans/scene0465_00/scene0465_00_vh_clean.ply'

data:
  input_folder: /home/yongqich/research/data/ScanNet/scans/scene0465_00
  output: /home/yongqich/research/GO-SLAM/output/scannet/0465/mono
