inherit_from: configs/ScanNet/scannet.yaml
mode: rgbd
mapping:
  device: "cuda:0"
  bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
meshing:
  gt_mesh_path: '/home/yongqich/research/data/ScanNet/scans/scene0169_00/scene0169_00_vh_clean.ply'
data:
  input_folder: /home/yongqich/research/data/ScanNet/scans/scene0169_00
  output: /home/yongqich/research/GO-SLAM/output/scannet/0169/rgbd
