inherit_from: ./configs/ScanNet/scannet.yaml
mode: rgbd
mapping:
  device: "cuda:0"
  bound: [[-7, 8], [-4, 6], [-8, 4]]

meshing:
  gt_mesh_path: '/home/yongqich/research/data/ScanNet/scans/scene0000_00/scene0000_00_vh_clean.ply'

data:
  input_folder: /home/yongqich/research/data/ScanNet/scans/scene0000_00
  output: /home/yongqich/research/GO-SLAM/output/scannet/0000/rgbd
