inherit_from: configs/Replica/replica_mono.yaml
mode: mono
mapping:
  bound: [[-2.0, 2.0], [-2.0, 2.0], [-2.0, 2.0]]
meshing:
  gt_mesh_path: Datasets/Replica/cull_replica_meshv2/office4.ply
data:
  input_folder: Datasets/Replica/office4
  output: output/Replica/office4/mono