inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping:
  bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: Datasets/Replica/cull_replica_meshv2/office2.ply
data:
  input_folder: Datasets/Replica/office2
  output: output/Replica/office2/rgbd