inherit_from: configs/Tum/tum.yaml
mapping:
  bound: [[-3.5,3],[-3,3],[-3,3]]
  marching_cubes_bound: [[-3.5,3],[-3,3],[-3,3]]
data:
  datadir: data/TUM/rgbd_dataset_self_1
  trainskip: 1
  output: output/TUM/fr_desk
  exp_name: demo

cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 612.2
  fy: 612.3
  cx: 324.7
  cy: 241.9
  crop_edge: 8
  crop_size: [480,640]
  distortion: [0.0, 0.0, 0.0, 0.0, 0.0] # https://community.intel.com/t5/Items-with-no-label/D435-Uncalibrated-Color-camera-distortion-coefficients-are-0-0-0/m-p/474740#M4583

extra:
  FR_DS: 2 # downsampling ratio for the frame rate
