inherit_from: configs/EuRoC/euroc.yaml
mode: stereo
only_tracking: False
mapping:
  bound: [[-4, 6], [-4, 4], [-10, 6]]
data:
  input_folder: /home/yongqich/research/data/EuRoC/V2_01_easy
  output: /home/yongqich/research/GO-SLAM/output/euroc/V2_01_easy
cam:
  H_out: 320
  W_out: 480

tracking:
  motion_filter:
    thresh: 8.0  # add as keyframe if avg flow >= 4.0 pixels
  frontend:
    keyframe_thresh: 8.0  # remove keyframe if avg flow < 4.0 pixels
    thresh: 16.0  # only consider edge with avg flow < 16.0 pixels
meshing:
  resolution: 1024  # change to 512 for higher resolution geometry
