inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  marching_cubes_bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  

data:
  datadir: data/neural_rgbd_data/breakfast_room
  trainskip: 3
  output: output/Synthetic/br_ds3
  exp_name: demo


cam:
  near: 0
  far: 5

extra:
  FR_DS: 2 # downsampling ratio for the frame rate
